settings:
  name: "Product Name"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  release_notes_autogen:
    auto_release_notes_enabled: true
    repositories_features:
      - workload-fsx-ontap
      - # second feature repo  

sidebar: 
  entries:
  - title: Legal notices
    url: /legal-notices.html
