settings:
  name: "Release notes"
  rss_page: "whats-new.html"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  release_notes_autogen:
    auto_release_notes_enabled: true
    repositories_features:
      - workload-fsx-ontap
      - workload-databases
      - workload-vmware
      - workload-genai 
      - workload-setup-admin

sidebar: 
  entries:
  - title: Workload Factory release notes
    url: /index.html
  - title: Recent changes 
    url: /whats-new.html 
  - title: Legal notices
    url: /legal-notices.html
product-family:
  name: Workload Factory
  repo: workload-family

