=== Snapshot and restore support for knowledge base volumes

You can now protect your Generative AI workloads data by taking a point-in-time copy of a knowledge base. This enables you to protect your data against accidental loss or test changes to the settings of the knowledge base. You can restore the previous version of the knowledge base volume at any time.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume[Take a snapshot of a knowledge base volume]

https://review.docs.netapp.com/us-en/workload-genai_29-sept-24-release/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume[Restore a snapshot of a knowledge base volume]

=== Pause scheduled scans

You can now pause scheduled data source scans. By default, Generative AI workloads scans each data source daily to ingest new data into each knowledge base. If you don't want the latest changes to be ingested (during testing or while restoring a snapshot, for example) you can pause the scheduled scans and resume them at any time.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html[Manage knowledge bases]

=== Data protection volumes now supported for knowledge bases
When selecting a knowledge base volume, you can now choose a data protection volume that is part of a NetApp SnapMirror replication relationship. This enables you to store knowledge bases on volumes that are already protected by SnapMirror replication.

https://docs.netapp.com/us-en/workload-genai/identify-data-sources.html[Identify the data sources to integrate in your knowledge base]

// Use absolute links or use relative links with no ../ to uplevel:
// link:manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume[Take a snapshot of a knowledge base volume-same-level]