=== BlueXP workload factory notification service support
The BlueXP workload factory notification service enables workload factory to send notifications to the BlueXP alerts service or to an Amazon SNS topic. Notifications sent to BlueXP alerts appear in the BlueXP alerts panel. When workload factory publishes notifications to an Amazon SNS topic, subscribers to the topic (such as people or other applications) receive the notifications at the endpoints configured for the topic (such as email or SMS messages).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html[Configure BlueXP workload factory notifications^]

Workload factory provides the following notifications for Databases:

* Well-architected report
* Host deployment
* Protection

=== Onboarding enhancement for registering instances

Workload factory for Databases has improved its onboarding process for registering instances running on Amazon FSx for NetApp ONTAP storage. You can now select instances in bulk for registration. Once an instance is registered, you can create and manage database host resources within the workload factory console. 

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html[Instance management]

=== Analysis and fix for Microsoft Multipath I/O timeout setting

The well-architected status for your database host instances now includes the analysis and the fix for the Microsoft Multipath I/O (MPIO) timeout setting. Setting the MPIO timeout to 60 seconds ensures FSx for ONTAP storage connectivity and stability during failovers. If the MPIO setting isn't set accordingly, workload factory will provide a fix to set the MPIO timeout value to 60 seconds.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html[Implement well-architected database configurations in workload factory]

=== Enhancements to graphics in host inventory

From the host inventory screen, various resource utilization graphs like throughput and IOPS now display 7 days of data so that you can monitor performance of SQL nodes from the workload factory console more efficiently. The performance metrics gathered from the SQL nodes will be saved in Amazon CloudWatch which can be used for Logs Insights or integrating with other analytic services in your environment.

From the Instances and Databases tabs within the host inventory, we've enhanced the description and visualization for host protection.
 
=== Support for Windows authentication in workload factory

Now workload factory supports SQL Server authentication using Windows authenticated users to register host instances and benefit from host management features. 

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html[Register host instances in workload factory for Databases]